### ISSUE TITLE
POM missing warning for v2.12.2

### ISSUE THREAD

**Issue by rakeshk15** [FasterXML/jackson-jaxrs-providers#138] opened 2021-03-04 03:26 UTC
I just updated to v2.12.2 and got these warning while building.

`Downloading from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jaxrs/jackson-jaxrs-base/2.12.2/jackson-jaxrs-base-2.12.2.pom
[WARNING] The POM for com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.12.2 is missing, no dependency information available
Downloading from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jaxrs/2.12.2/jackson-datatype-jaxrs-2.12.2.pom
[WARNING] The POM for com.fasterxml.jackson.datatype:jackson-datatype-jaxrs:jar:2.12.2 is missing, no dependency information available
Downloading from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.12.2/jackson-jaxrs-json-provider-2.12.2.pom
[WARNING] The POM for com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.12.2 is missing, no dependency information available
Downloading from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jsr353/2.12.2/jackson-datatype-jsr353-2.12.2.pom
[WARNING] The POM for com.fasterxml.jackson.datatype:jackson-datatype-jsr353:jar:2.12.2 is missing, no dependency information available`

**Comment by cowtowncoder** [comment] 2021-03-04 04:39
This may happen during release process since it is not atomic. In future you may want to wait until upgrading when a new release is going out: announcements go on Twitter via `@FasterXML` as well on mailing list like https://groups.google.com/forum/#!forum/jackson-announce

**Comment by rakeshk15** [comment] 2021-03-04 04:49
sure @cowtowncoder 

I saw the artifacts in maven central and seems it was released a while ago (this is the timestamp but I don't know the timezone : 2021-03-03 23:11) so I thought to update my dependencies. I raised this issue just to be sure that there is no issue in released artifacts.

Also, when I release something to central repo it is available in 10-15 mins.

But that's ok, will take care next time.

**Comment by rakeshk15** [comment] 2021-03-04 04:54
Not sure if you closely looked at the logs I shared, its just the POM which is missing, I could see jars in central repo.

`https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jaxrs/jackson-jaxrs-base/2.12.2`

So I am just wondering why only POM is missing.

**Comment by cowtowncoder** [comment] 2021-03-04 05:06
Oh fuck. Did Maven Central manage to break up the release again somehow? Closing and releasing succeeded just fine and yet... it does look as if pom was magically missing.

**Comment by cowtowncoder** [comment] 2021-03-04 05:20
Poms seem to be missing from actual providers as well.

**Comment by cowtowncoder** [comment] 2021-03-04 06:39
Filed: https://issues.sonatype.org/browse/MVNCENTRAL-6595

**Comment by cowtowncoder** [comment] 2021-03-04 07:01
Suspecting this is due to #136, since I noticed that the `jackson-datatype-jsr353`:

https://repo.maven.apache.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jsr353/2.12.2/

is similarly broken. I do not understand why Nexus allows closing and releasing of such artifact set (seems like a broken set); and also why is build itself broken...
What I horrible fucking mess. Thank you for reporting it, I just hate when things get corrupt.

**Comment by ilgrosso** [comment] 2021-03-04 14:16
FTR the pom is also missing from https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.12.2/

**Comment by cowtowncoder** [comment] 2021-03-04 15:22
@ilgrosso yes, every artifact that has javax->jakarta classifier has this problem unfortunately, it seems.

**Comment by megglos** [comment] 2021-03-04 15:46
Just to get an understanding on how to go forward, is the current state of this that you try to clarify this with maven central and the missing pom may get added and it will eventually be there? Or is it more likely that due to this being possibly caused by #136 that there will be a 2.12.3 patch?

**Comment by cowtowncoder** [comment] 2021-03-04 15:54
@megglos My guess at this point is that I'll probably have to do 2.12.2.1 micro-path for JAX-RS and jsr-353 first, as a sort of hotfix. And then once everything is verified, settled, 2.12.3, quite soon after. I am not sure it will be feasible to retrofit 2.12.2 that got out due to the way Maven Central syncing works.

**Comment by cowtowncoder** [comment] 2021-03-05 18:34
On JSON-P: I went ahead and merged alternative patch so that there are now separate jars:

1. `jackson-datatype-jsr353`, the old existing jar (... with broken 2.12.2 variant, wrt pom, unfortunately) -- I am working with Sonatype admins to fix 2.12.2 version
2. `jackson-datatype-jakarta-jsonp`: a copy of former but for "jakarta.json" types. 2.12.2 version is released (although with limited testing).

For JAX-RS I hope we can make classifier approach working, at least for 2.12.x/2.13 timeframe. While amount of code is not humongous, I'd prefer not forking codebase there.

**Comment by GedMarc** [comment] 2021-03-06 11:52
OK I've set up an artifactory with similar rules to sonar-nexus - going to push it all through there and see

**Comment by cowtowncoder** [comment] 2021-03-06 17:00
Update: I re-ran release up to upload, but no close with Nexus staging plugin; information added to https://issues.sonatype.org/browse/MVNCENTRAL-6595 . No problem reported on client side logs, seems to include pom, so would seem likely Nexus dropping poms (but obviously not proof; release plugin could be dropping it).

**Comment by GedMarc** [comment] 2021-03-07 17:50
@cowtowncoder The OSGi change must get rolled back for these - 

The second felix bundle run is removing the original pom "bundle" artefact - it's deploying through to nexus because of the jakarta namespace pom file which it is referencing, and then attaches the standard jar there-after 

I haven't found a solution as yet

**Comment by cowtowncoder** [comment] 2021-03-07 22:58
@GedMarc It makes sense that bundle run could be the cause here. But it still seems quite odd that .pom would be disappearing, instead of .jar (bundle)?

I am hoping to hear back from Sonatype tomorrow (monday), but I suspect it may be necessary like you say to just remove OSGi re-processing, esp. on short term. It is not a major use case and was not working before changes anyway.

It would also be good to know how quickly J2EE downstream systems are moving to Jakarta dependencies. Since JAX-RS provider code base has not moved very fast, it might be acceptable to duplicate projects (if absolutely necessary), if one of them can be deprecated in near future. But I don't really have a sense of that, or even on how widely these providers are used. Spring Boot does not use them, I think; and I don't know if JAX-RS providers might have their own implementations.

**Comment by cowtowncoder** [comment] 2021-03-08 19:19
@GedMarc as per update by Joel on https://issues.sonatype.org/browse/MVNCENTRAL-6595 I think there are 2 things to consider:

1. If there's any chance that there's a newer plug-in version for plug-ins relevant (bundle, shade?), I can try upgrade to latest and see if that helps at all
2. if the issue cannot be resolved, need to undo changes to produce working Jakarta/OSGi variants for 2.12 at least.

**Comment by cowtowncoder** [comment] 2021-03-08 20:59
Looking at plugin versions for 2.12 branch, we have latest available versions for 3 that seem most relevant:

* `maven-bundle-plugin`: 5.1.1 (for OSGi manifest)
* `maven-shade-plugin`: 3.2.4
* `maven-jar-plugin`: 3.2.0

so none of those would be candidate for upgrading.

**Comment by krusche** [comment] 2021-03-09 21:57
our Gradle build does not work any more when we update to 2.12.2 so we do not get a warning but an error. Will revert to 2.12.1 until this is fixed

```
error	09-Mar-2021 21:41:13	Execution failed for task ':compileJava'.
error	09-Mar-2021 21:41:13	> Could not resolve all files for configuration ':compileClasspath'.
error	09-Mar-2021 21:41:13	   > Could not find com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:2.12.2.
error	09-Mar-2021 21:41:13	     Searched in the following locations:
error	09-Mar-2021 21:41:13	       - file:/root/.m2/repository/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.12.2/jackson-jaxrs-json-provider-2.12.2.pom
error	09-Mar-2021 21:41:13	       - https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.12.2/jackson-jaxrs-json-provider-2.12.2.pom
error	09-Mar-2021 21:41:13	       - https://jcenter.bintray.com/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.12.2/jackson-jaxrs-json-provider-2.12.2.pom
error	09-Mar-2021 21:41:13	     Required by:
error	09-Mar-2021 21:41:13	         project : > io.github.jhipster:jhipster-dependencies:3.9.1
error	09-Mar-2021 21:41:13	   > Could not find com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:2.12.2.
error	09-Mar-2021 21:41:13	     Searched in the following locations:
error	09-Mar-2021 21:41:13	       - file:/root/.m2/repository/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.12.2/jackson-jaxrs-json-provider-2.12.2.pom
error	09-Mar-2021 21:41:13	       - https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.12.2/jackson-jaxrs-json-provider-2.12.2.pom
error	09-Mar-2021 21:41:13	       - https://jcenter.bintray.com/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.12.2/jackson-jaxrs-json-provider-2.12.2.pom
error	09-Mar-2021 21:41:13	     Required by:
error	09-Mar-2021 21:41:13	         project : > org.gitlab4j:gitlab4j-api:4.15.7
error	09-Mar-2021 21:41:13	   > Could not find com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:2.12.2.
error	09-Mar-2021 21:41:13	     Searched in the following locations:
error	09-Mar-2021 21:41:13	       - file:/root/.m2/repository/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.12.2/jackson-jaxrs-json-provider-2.12.2.pom
error	09-Mar-2021 21:41:13	       - https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.12.2/jackson-jaxrs-json-provider-2.12.2.pom
error	09-Mar-2021 21:41:13	       - https://jcenter.bintray.com/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.12.2/jackson-jaxrs-json-provider-2.12.2.pom
error	09-Mar-2021 21:41:13	     Required by:
error	09-Mar-2021 21:41:13	         project : > com.fasterxml.jackson.datatype:jackson-datatype-hppc:2.12.2 > com.fasterxml.jackson:jackson-bom:2.12.2
```

**Comment by cowtowncoder** [comment] 2021-03-10 00:09
Created #139 to undo changes, but hoping @GedMarc can sanity check before proceeding with another release attempt.

**Comment by cowtowncoder** [comment] 2021-03-11 03:04
Merging the PR, published fixed (I hope!) 2.12.2 to Sonatype OSS staging; hoping we can get this resolved soon.

**Comment by GedMarc** [comment] 2021-03-11 03:26
sorry man! the bread and milk job is swallowing all time! :(

**Comment by cowtowncoder** [comment] 2021-03-11 03:28
@GedMarc np at all; figured that I can easily try it out. I know the "that which pays for mortgage" situation. :)

**Comment by cowtowncoder** [comment] 2021-03-12 04:29
Republish complete, Nexus sync to Maven Central as well: .pom files should now finally be available.

Unfortunately this means that OSGi bundle metadata is wrong (same as with 2.12.1), but there is no avoiding that without finding some other mechanism, or figuring out what exactly is/was wrong with post-processing.

**Closed by cowtowncoder** 2021-03-12 04:29 UTC

**Comment by ilgrosso** [comment] 2021-03-12 06:54
Thanks @cowtowncoder !

**Comment by caleb-adams** [comment] 2021-03-16 17:54
Confirmed this has resolved our build issues. Thank you @cowtowncoder !
