### ISSUE TITLE
JacksonJaxbJsonProvider setTimeZone not working

### ISSUE THREAD

**Issue by hieuhcmus** [FasterXML/jackson-jaxrs-providers#62] opened 2015-04-14 02:25 UTC
It seems to be that the function setTimeZone of JacksonJaxbJsonProvider does not work correctly.
I want to set the timezone to default timezone instead of GMT, but it didn't work

```
@Provider
@Produces(MediaType.APPLICATION_JSON)
class JacksonConfig extends JacksonJaxbJsonProvider {
    public JacksonConfig() {
        ObjectMapper mapper = new ObjectMapper();
        mapper.setSerializationInclusion(Include.NON_NULL);
        mapper.setTimeZone(TimeZone.getDefault());
        super.setMapper(mapper);
    }
}
```

When I change it to general way using ContextResolver, it worked

```
@Provider
@Produces(MediaType.APPLICATION_JSON)
public class JacksonConfig implements ContextResolver<ObjectMapper> {
    private ObjectMapper mapper;
    public JacksonConfig() {
        mapper = new ObjectMapper();
        mapper.setSerializationInclusion(Include.NON_NULL);
        mapper.setTimeZone(TimeZone.getDefault());
    }
    @Override
    public ObjectMapper getContext(Class<?> type) {
        return mapper;
    }
}
```

**Comment by cowtowncoder** [comment] 2015-04-22 06:20
I assume the problem is more in that configured `ObjectMapper` is not being used, and not so much about timezone configuration. Which JAX-RS implementation is this with? (or, wrapper framework, if one used, like DropWizard or Spring Boot).

**Comment by hieuhcmus** [comment] 2015-04-22 06:45
I am using Resteasy

**Comment by cowtowncoder** [comment] 2015-04-22 23:31
Ok thanks. Not sure if it is relevant, but good to know. If there is a way to provide a simple unit test, that'd be great.

**Comment by cowtowncoder** [comment] 2017-07-28 03:39
Can not reproduce closing.

**Closed by cowtowncoder** 2017-07-28 03:39 UTC
